pipeline {
    agent any
    triggers {
        githubPush()
    }
    stages {
        stage('Restore packages'){
           steps{
               sh 'dotnet restore SimpleApp/SimpleApp.sln'
            }
         }
        stage('Clean'){
           steps{
               sh 'dotnet clean SimpleApp/SimpleApp.sln --configuration Release'
            }
         }
        stage('Build'){
           steps{
               sh 'dotnet build SimpleApp/SimpleApp.sln --configuration Release --no-restore'
            }
         }
        stage('Test: Unit Test'){
           steps {
                sh 'dotnet test SimpleApp/UnitTets/UnitTests.csproj --configuration Release --no-restore'
             }
          }
    }
}